palette = "melange"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
truncation_length = 4
style = "bold light_blue"

[git_branch]
format = "[$branch]($style)"
style = "ui"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "light_cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "ui"

[palettes.melange]
ui = "#867462"
red = "#bd8183"
yellow = "#e49b5d"
green = "#78997a"
light_cyan = "#89b3b6"
light_blue = "#a3a9ce"
