theme = "melange"

[editor]
bufferline = "always"
line-number = "relative"
true-color = true
color-modes = true
# auto-info = false
auto-format = true
cursorline = true
completion-trigger-len = 1

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
  "mode",
  "spacer",
  "file-name",
  "spacer",
  "diagnostics",
  "workspace-diagnostics",
]
right = [
  "version-control",
  "spacer",
  "position",
  "position-percentage",
  "spacer",
]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
x = "extend_line"
esc = ["collapse_selection", "keep_primary_selection"]
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
C-s = ":write"
C-r = ":config-reload"

[keys.normal.space]
q = ":buffer-close"
Q = ":buffer-close!"
l = ":toggle lsp.display-inlay-hints"

[keys.select]
x = "extend_line"
";" = ["collapse_selection", "normal_mode"]
