theme = "catppuccin_macchiato"

[editor]
bufferline = "always"
true-color = true
color-modes = true
# auto-info = false
auto-format = true
cursorline = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "file-name", "diagnostics"]
right = ["version-control", "position", "position-percentage"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
C-s = ":w"
C-q = ":bc"
X = "extend_line_above"
