[astronvim.files]
"astronvim/" = "~/.config/nvim/lua/user/"

[bat.files]
"bat/" = "~/.config/bat/"

[fish.files]
"fish/" = "~/.config/fish/"

[starship.files]
"starship.toml" = "~/.config/starship.toml"
