[bat.files]
"bat/" = "~/.config/bat/"

[fish.files]
"fish/" = "~/.config/fish/"

[fish.variables]
# Set the machine name.
hostname = ""

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[gitui.files]
"gitui/" = "~/.config/gitui/"
