[helix.files]
"helix/" = "~/.config/helix/"

[bat.files]
"bat/" = "~/.config/bat/"

[fish.files]
"fish/" = "~/.config/fish/"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[zellij.files]
"zellij/" = "~/.config/zellij/"

[alacritty.files]
"alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[waybar.files]
"waybar/" = "~/.config/waybar/"

[hyprland.files]
"hypr/" = "~/.config/hypr/"
